package server

import (
	"github.com/go-chi/chi/v5"
	"net/http"
)

func (s *Server) mountUIRoutes(r chi.Router) {
	r.Get("/login", s.uiLoginPage)
	r.Post("/login", s.uiLogin)
	r.Post("/login/passkey/options", s.uiPasskeyLoginOptions)
	r.Post("/login/passkey", s.uiPasskeyLogin)
	r.Get("/signup", s.uiSignupPage)
	r.Post("/signup", s.uiSignup)
	r.Post("/signup/passkey/options", s.uiPasskeySignupOptions)
	r.Post("/signup/passkey", s.uiPasskeySignup)
	r.Post("/logout", s.uiLogout)

	r.Group(func(r chi.Router) {
		r.Use(s.uiAuthMiddleware)
		r.Get("/", s.uiHome)
		r.Get("/me", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPage(w, r, "active") })
		r.Get("/me/panel", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPanel(w, r, "active") })
		r.Get("/me/all", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPage(w, r, "all") })
		r.Get("/me/all/panel", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPanel(w, r, "all") })
		r.Get("/projects", s.uiProjectsPage)
		r.Get("/projects/panel", s.uiProjectsPanel)
		r.Get("/projects/new", s.uiNewProjectPage)
		r.Get("/projects/new/panel", s.uiNewProjectPanel)
		r.Post("/projects", s.uiCreateProject)
		r.Get("/issues/new", s.uiNewIssuePage)
		r.Get("/issues/new/panel", s.uiNewIssuePanel)
		r.Get("/issues/new/projects", s.uiNewIssueProjectOptions)
		r.Post("/issues", s.uiCreateIssue)
		r.Get("/settings", s.uiSettingsPage)
		r.Post("/settings/profile", s.uiUpdateProfile)
		r.Post("/settings/profile-image", s.uiUpdateProfileImage)
		r.Post("/settings/profile-image/delete", s.uiDeleteProfileImage)
		r.Post("/settings/password", s.uiUpdatePassword)
		r.Post("/settings/password-login", s.uiUpdatePasswordLogin)
		r.Post("/settings/passkeys/reauth/password", s.uiPasskeyPasswordReauth)
		r.Post("/settings/passkeys/reauth/passkey/options", s.uiPasskeyReauthOptions)
		r.Post("/settings/passkeys/reauth/passkey", s.uiPasskeyReauth)
		r.Post("/settings/passkeys/options", s.uiPasskeyAddOptions)
		r.Post("/settings/passkeys", s.uiPasskeyAdd)
		r.Post("/settings/passkeys/{id}/revoke", s.uiPasskeyRevoke)
		r.Get("/tokens", s.uiTokensPage)
		r.Post("/tokens", s.uiCreateToken)
		r.Post("/tokens/{id}/revoke", s.uiRevokeToken)
		r.Get("/users/{id}/profile-image/content", s.uiGetUserProfileImageContent)
		r.Get("/users/{id}/profile-image/thumbnail/content", s.uiGetUserProfileImageThumbnailContent)
		if s.hub != nil {
			r.Get("/realtime", s.uiRealtime)
		}
		r.Get("/{owner}/issues/{issueRef}", s.uiIssuePage)
		r.Get("/{owner}/issues/{issueRef}/panel", s.uiIssuePanel)
		r.Post("/{owner}/issues/{issueRef}/delete", s.uiIssueWriteHandler(s.uiDeleteIssue))
		r.Post("/{owner}/issues/{issueRef}/restore", s.uiIssueWriteHandler(s.uiRestoreIssue))
		r.Get("/{owner}/issues/{issueRef}/title/edit", s.uiIssueWriteHandler(s.uiEditIssueTitle))
		r.Post("/{owner}/issues/{issueRef}/title", s.uiIssueWriteHandler(s.uiUpdateIssueTitle))
		r.Get("/{owner}/issues/{issueRef}/description/edit", s.uiIssueWriteHandler(s.uiEditIssueDescription))
		r.Post("/{owner}/issues/{issueRef}/description", s.uiIssueWriteHandler(s.uiUpdateIssueDescription))
		r.Get("/{owner}/issues/{issueRef}/status/edit", s.uiIssueWriteHandler(s.uiEditIssueStatus))
		r.Post("/{owner}/issues/{issueRef}/status", s.uiIssueWriteHandler(s.uiUpdateIssueStatus))
		r.Get("/{owner}/issues/{issueRef}/close-reason/edit", s.uiIssueWriteHandler(s.uiEditIssueCloseReason))
		r.Post("/{owner}/issues/{issueRef}/close-reason", s.uiIssueWriteHandler(s.uiUpdateIssueCloseReason))
		r.Get("/{owner}/issues/{issueRef}/priority/edit", s.uiIssueWriteHandler(s.uiEditIssuePriority))
		r.Post("/{owner}/issues/{issueRef}/priority", s.uiIssueWriteHandler(s.uiUpdateIssuePriority))
		r.Get("/{owner}/issues/{issueRef}/due-date/edit", s.uiIssueWriteHandler(s.uiEditIssueDueDate))
		r.Post("/{owner}/issues/{issueRef}/due-date", s.uiIssueWriteHandler(s.uiUpdateIssueDueDate))
		r.Get("/{owner}/issues/{issueRef}/assignee/edit", s.uiIssueWriteHandler(s.uiEditIssueAssignee))
		r.Post("/{owner}/issues/{issueRef}/assignee", s.uiIssueWriteHandler(s.uiUpdateIssueAssignee))
		r.Get("/{owner}/issues/{issueRef}/reporter/edit", s.uiIssueWriteHandler(s.uiEditIssueReporter))
		r.Post("/{owner}/issues/{issueRef}/reporter", s.uiIssueWriteHandler(s.uiUpdateIssueReporter))
		r.Get("/{owner}/issues/{issueRef}/sprint/edit", s.uiIssueWriteHandler(s.uiEditIssueSprint))
		r.Post("/{owner}/issues/{issueRef}/sprint", s.uiIssueWriteHandler(s.uiUpdateIssueSprint))
		r.Get("/{owner}/issues/{issueRef}/links/new", s.uiIssueWriteHandler(s.uiNewIssueLink))
		r.Post("/{owner}/issues/{issueRef}/links", s.uiIssueWriteHandler(s.uiCreateIssueLink))
		r.Get("/{owner}/issues/{issueRef}/links/{linkRef}/edit", s.uiIssueWriteHandler(s.uiEditIssueLink))
		r.Post("/{owner}/issues/{issueRef}/links/{linkRef}", s.uiIssueWriteHandler(s.uiUpdateIssueLink))
		r.Post("/{owner}/issues/{issueRef}/links/{linkRef}/delete", s.uiIssueWriteHandler(s.uiDeleteIssueLink))
		r.Get("/{owner}/issues/{issueRef}/sub-issues/new", s.uiIssueWriteHandler(s.uiNewSubIssue))
		r.Post("/{owner}/issues/{issueRef}/sub-issues", s.uiIssueWriteHandler(s.uiCreateSubIssue))
		r.Post("/{owner}/issues/{issueRef}/comments", s.uiIssueWriteHandler(s.uiCreateComment))
		r.Get("/{owner}/issues/{issueRef}/comments/{commentRef}/edit", s.uiIssueWriteHandler(s.uiEditComment))
		r.Post("/{owner}/issues/{issueRef}/comments/{commentRef}", s.uiIssueWriteHandler(s.uiUpdateComment))
		r.Post("/{owner}/issues/{issueRef}/attachments", s.uiIssueWriteHandler(s.uiCreateIssueAttachment))
		r.Get("/{owner}/issues/{issueRef}/attachments/{objectRef}/content", s.uiGetIssueAttachmentContent)
		r.Post("/{owner}/issues/{issueRef}/attachments/{objectRef}/delete", s.uiIssueWriteHandler(s.uiDeleteIssueAttachment))
		r.Delete("/{owner}/issues/{issueRef}/attachments/{objectRef}", s.uiIssueWriteHandler(s.uiDeleteIssueAttachmentJSON))
		r.Get("/{owner}/issues/{issueRef}/context", s.uiViewIssueContext)
		r.Get("/{owner}/issues/{issueRef}/context/link", s.uiIssueWriteHandler(s.uiNewIssueContextLink))
		r.Get("/{owner}/issues/{issueRef}/context/new", s.uiIssueWriteHandler(s.uiNewIssueContext))
		r.Post("/{owner}/issues/{issueRef}/context", s.uiIssueWriteHandler(s.uiCreateIssueContextLink))
		r.Get("/{owner}/issues/{issueRef}/context/{contextRef}", s.uiViewIssueContextItem)
		r.Get("/{owner}/issues/{issueRef}/context/{contextRef}/edit", s.uiIssueWriteHandler(s.uiEditIssueContext))
		r.Post("/{owner}/issues/{issueRef}/context/{contextRef}", s.uiIssueWriteHandler(s.uiUpdateIssueContext))
		r.Post("/{owner}/issues/{issueRef}/context/{contextRef}/delete", s.uiIssueWriteHandler(s.uiDeleteIssueContextLink))
		r.Get("/{owner}/issues/{issueRef}/tags", s.uiIssueWriteHandler(s.uiIssueTagsPage))
		r.Post("/{owner}/issues/{issueRef}/tags", s.uiIssueWriteHandler(s.uiAttachIssueTag))
		r.Post("/{owner}/issues/{issueRef}/tags/{tagRef}/delete", s.uiIssueWriteHandler(s.uiDetachIssueTag))
		r.Get("/{owner}/projects/{key}", s.uiProjectPage)
		r.Get("/{owner}/projects/{key}/about", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "about") })
		r.Get("/{owner}/projects/{key}/about/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "about") })
		r.Post("/{owner}/projects/{key}/image", s.uiUpdateProjectImage)
		r.Post("/{owner}/projects/{key}/image/delete", s.uiDeleteProjectImage)
		r.Get("/{owner}/projects/{key}/image/content", s.uiGetProjectImageContent)
		r.Get("/{owner}/projects/{key}/image/thumbnail/content", s.uiGetProjectImageThumbnailContent)
		r.Get("/{owner}/projects/{key}/tags", s.uiProjectTagsPage)
		r.Post("/{owner}/projects/{key}/tags", s.uiProjectWriteHandler(s.uiCreateProjectTag))
		r.Get("/{owner}/projects/{key}/tags/{tagRef}/edit", s.uiProjectWriteHandler(s.uiEditProjectTag))
		r.Post("/{owner}/projects/{key}/tags/{tagRef}", s.uiProjectWriteHandler(s.uiUpdateProjectTag))
		r.Post("/{owner}/projects/{key}/tags/{tagRef}/delete", s.uiProjectWriteHandler(s.uiDeleteProjectTag))
		r.Get("/{owner}/projects/{key}/context", s.uiProjectContextPage)
		r.Get("/{owner}/projects/{key}/context/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "context") })
		r.Get("/{owner}/projects/{key}/context/new", s.uiProjectWriteHandler(s.uiNewProjectContext))
		r.Post("/{owner}/projects/{key}/context", s.uiProjectWriteHandler(s.uiCreateProjectContext))
		r.Get("/{owner}/projects/{key}/context/{contextRef}", s.uiViewProjectContext)
		r.Get("/{owner}/projects/{key}/context/{contextRef}/panel", s.uiViewProjectContext)
		r.Get("/{owner}/projects/{key}/context/{contextRef}/edit", s.uiProjectWriteHandler(s.uiEditProjectContext))
		r.Post("/{owner}/projects/{key}/context/{contextRef}", s.uiProjectWriteHandler(s.uiUpdateProjectContext))
		r.Post("/{owner}/projects/{key}/context/{contextRef}/delete", s.uiProjectWriteHandler(s.uiDeleteProjectContext))
		r.Post("/{owner}/projects/{key}/context/{contextRef}/move-up", s.uiProjectWriteHandler(s.uiMoveProjectContextUp))
		r.Post("/{owner}/projects/{key}/context/{contextRef}/move-down", s.uiProjectWriteHandler(s.uiMoveProjectContextDown))
		r.Post("/{owner}/projects/{key}/context/{contextRef}/attachments", s.uiProjectWriteHandler(s.uiCreateContextAttachment))
		r.Get("/{owner}/projects/{key}/context/{contextRef}/attachments/{objectRef}/content", s.uiGetContextAttachmentContent)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/attachments/{objectRef}/delete", s.uiProjectWriteHandler(s.uiDeleteContextAttachment))
		r.Delete("/{owner}/projects/{key}/context/{contextRef}/attachments/{objectRef}", s.uiProjectWriteHandler(s.uiDeleteContextAttachmentJSON))
		r.Get("/{owner}/projects/{key}/context/{contextRef}/issues/new", s.uiProjectWriteHandler(s.uiNewProjectContextIssueLink))
		r.Post("/{owner}/projects/{key}/context/{contextRef}/issues", s.uiProjectWriteHandler(s.uiCreateProjectContextIssueLink))
		r.Post("/{owner}/projects/{key}/context/{contextRef}/issues/{issueRef}/delete", s.uiProjectWriteHandler(s.uiDeleteProjectContextIssueLink))
		r.Get("/{owner}/projects/{key}/name/edit", s.uiProjectWriteHandler(s.uiEditProjectName))
		r.Post("/{owner}/projects/{key}/name", s.uiProjectWriteHandler(s.uiUpdateProjectName))
		r.Post("/{owner}/projects/{key}/favorite", s.uiToggleProjectFavorite)
		r.Get("/{owner}/projects/{key}/members", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "members") })
		r.Get("/{owner}/projects/{key}/members/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "members") })
		r.Post("/{owner}/projects/{key}/members", s.uiAddProjectMember)
		r.Post("/{owner}/projects/{key}/members/{username}", s.uiUpdateProjectMember)
		r.Post("/{owner}/projects/{key}/members/{username}/delete", s.uiDeleteProjectMember)
		r.Get("/{owner}/projects/{key}/description/edit", s.uiProjectWriteHandler(s.uiEditProjectDescription))
		r.Post("/{owner}/projects/{key}/description", s.uiProjectWriteHandler(s.uiUpdateProjectDescription))
		r.Post("/{owner}/projects/{key}/attachments", s.uiProjectWriteHandler(s.uiCreateProjectAttachment))
		r.Get("/{owner}/projects/{key}/attachments/{objectRef}/content", s.uiGetProjectAttachmentContent)
		r.Post("/{owner}/projects/{key}/attachments/{objectRef}/delete", s.uiProjectWriteHandler(s.uiDeleteProjectAttachment))
		r.Delete("/{owner}/projects/{key}/attachments/{objectRef}", s.uiProjectWriteHandler(s.uiDeleteProjectAttachmentJSON))
		r.Get("/{owner}/projects/{key}/sprints", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "sprints") })
		r.Get("/{owner}/projects/{key}/sprints/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "sprints") })
		r.Get("/{owner}/projects/{key}/sprints/page", s.uiProjectSprintHistoryPage)
		r.Get("/{owner}/projects/{key}/sprints/new", s.uiProjectWriteHandler(s.uiNewProjectSprint))
		r.Post("/{owner}/projects/{key}/sprints", s.uiProjectWriteHandler(s.uiCreateProjectSprint))
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/history/issues", s.uiProjectSprintHistoryIssues)
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/edit", s.uiProjectWriteHandler(s.uiEditProjectSprint))
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/description", s.uiProjectSprintDescription)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}", s.uiProjectWriteHandler(s.uiUpdateProjectSprint))
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/attachments", s.uiProjectWriteHandler(s.uiCreateSprintAttachment))
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/attachments/{objectRef}/content", s.uiGetSprintAttachmentContent)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/attachments/{objectRef}/delete", s.uiProjectWriteHandler(s.uiDeleteSprintAttachment))
		r.Delete("/{owner}/projects/{key}/sprints/{sprintRef}/attachments/{objectRef}", s.uiProjectWriteHandler(s.uiDeleteSprintAttachmentJSON))
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/activate", s.uiProjectWriteHandler(s.uiActivateProjectSprint))
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/complete", s.uiProjectWriteHandler(s.uiCompleteProjectSprint))
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/delete", s.uiProjectWriteHandler(s.uiDeleteProjectSprint))
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/move-up", s.uiProjectWriteHandler(s.uiMoveProjectSprintUp))
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/move-down", s.uiProjectWriteHandler(s.uiMoveProjectSprintDown))
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/issues/new", s.uiProjectWriteHandler(s.uiNewProjectSprintIssue))
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/issues", s.uiProjectWriteHandler(s.uiAddProjectSprintIssue))
		r.Get("/{owner}/projects/{key}/issues/new", s.uiProjectWriteHandler(s.uiNewProjectIssuePage))
		r.Get("/{owner}/projects/{key}/issues/new/panel", s.uiProjectWriteHandler(s.uiNewProjectIssuePanel))
		r.Post("/{owner}/projects/{key}/issues", s.uiProjectWriteHandler(s.uiCreateProjectIssue))
		r.Get("/{owner}/projects/{key}/sprint", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "sprint") })
		r.Get("/{owner}/projects/{key}/sprint/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "sprint") })
		r.Get("/{owner}/projects/{key}/planned", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "planned") })
		r.Get("/{owner}/projects/{key}/planned/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "planned") })
		r.Get("/{owner}/projects/{key}/all", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "all") })
		r.Get("/{owner}/projects/{key}/all/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "all") })
		r.Get("/{owner}/projects/{key}/all/page", s.uiProjectAllIssuePage)
		r.Get("/{owner}/projects/{key}/changelog", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "changelog") })
		r.Get("/{owner}/projects/{key}/changelog/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "changelog") })
		r.Get("/{owner}/projects/{key}/changelog/page", s.uiProjectChangelogPage)
		r.Get("/{owner}/projects/{key}/backlog", func(w http.ResponseWriter, r *http.Request) { s.uiProjectLegacyBacklog(w, r, false) })
		r.Get("/{owner}/projects/{key}/backlog/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectLegacyBacklog(w, r, true) })
		r.Get("/{owner}/projects/{key}/deleted", s.uiProjectDeletedPage)
		r.Get("/{owner}/projects/{key}/deleted/panel", s.uiProjectDeletedPanel)
	})
}
