package server

import (
	"github.com/go-chi/chi/v5"
	"net/http"
)

func (s *Server) mountUIRoutes(r chi.Router) {
	r.Get("/login", s.uiLoginPage)
	r.Post("/login", s.uiLogin)
	r.Post("/login/passkey/options", s.uiPasskeyLoginOptions)
	r.Post("/login/passkey", s.uiPasskeyLogin)
	r.Get("/signup", s.uiSignupPage)
	r.Post("/signup", s.uiSignup)
	r.Post("/signup/passkey/options", s.uiPasskeySignupOptions)
	r.Post("/signup/passkey", s.uiPasskeySignup)
	r.Post("/logout", s.uiLogout)

	r.Group(func(r chi.Router) {
		r.Use(s.uiAuthMiddleware)
		r.Get("/", s.uiHome)
		r.Get("/me", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPage(w, r, "active") })
		r.Get("/me/panel", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPanel(w, r, "active") })
		r.Get("/me/all", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPage(w, r, "all") })
		r.Get("/me/all/panel", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPanel(w, r, "all") })
		r.Get("/projects", s.uiProjectsPage)
		r.Get("/projects/panel", s.uiProjectsPanel)
		r.Get("/projects/new", s.uiNewProjectPage)
		r.Get("/projects/new/panel", s.uiNewProjectPanel)
		r.Post("/projects", s.uiCreateProject)
		r.Get("/issues/new", s.uiNewIssuePage)
		r.Get("/issues/new/panel", s.uiNewIssuePanel)
		r.Get("/issues/new/projects", s.uiNewIssueProjectOptions)
		r.Post("/issues", s.uiCreateIssue)
		r.Get("/settings", s.uiSettingsPage)
		r.Post("/settings/profile", s.uiUpdateProfile)
		r.Post("/settings/profile-image", s.uiUpdateProfileImage)
		r.Post("/settings/profile-image/delete", s.uiDeleteProfileImage)
		r.Post("/settings/password", s.uiUpdatePassword)
		r.Post("/settings/password-login", s.uiUpdatePasswordLogin)
		r.Post("/settings/passkeys/reauth/password", s.uiPasskeyPasswordReauth)
		r.Post("/settings/passkeys/reauth/passkey/options", s.uiPasskeyReauthOptions)
		r.Post("/settings/passkeys/reauth/passkey", s.uiPasskeyReauth)
		r.Post("/settings/passkeys/options", s.uiPasskeyAddOptions)
		r.Post("/settings/passkeys", s.uiPasskeyAdd)
		r.Post("/settings/passkeys/{id}/revoke", s.uiPasskeyRevoke)
		r.Get("/tokens", s.uiTokensPage)
		r.Post("/tokens", s.uiCreateToken)
		r.Post("/tokens/{id}/revoke", s.uiRevokeToken)
		r.Get("/users/{id}/profile-image/content", s.uiGetUserProfileImageContent)
		r.Get("/users/{id}/profile-image/thumbnail/content", s.uiGetUserProfileImageThumbnailContent)
		if s.hub != nil {
			r.Get("/realtime", s.uiRealtime)
		}
		r.Get("/{owner}/issues/{issueRef}", s.uiIssuePage)
		r.Get("/{owner}/issues/{issueRef}/panel", s.uiIssuePanel)
		r.Post("/{owner}/issues/{issueRef}/delete", s.uiDeleteIssue)
		r.Post("/{owner}/issues/{issueRef}/restore", s.uiRestoreIssue)
		r.Get("/{owner}/issues/{issueRef}/title/edit", s.uiEditIssueTitle)
		r.Post("/{owner}/issues/{issueRef}/title", s.uiUpdateIssueTitle)
		r.Get("/{owner}/issues/{issueRef}/description/edit", s.uiEditIssueDescription)
		r.Post("/{owner}/issues/{issueRef}/description", s.uiUpdateIssueDescription)
		r.Get("/{owner}/issues/{issueRef}/status/edit", s.uiEditIssueStatus)
		r.Post("/{owner}/issues/{issueRef}/status", s.uiUpdateIssueStatus)
		r.Get("/{owner}/issues/{issueRef}/close-reason/edit", s.uiEditIssueCloseReason)
		r.Post("/{owner}/issues/{issueRef}/close-reason", s.uiUpdateIssueCloseReason)
		r.Get("/{owner}/issues/{issueRef}/priority/edit", s.uiEditIssuePriority)
		r.Post("/{owner}/issues/{issueRef}/priority", s.uiUpdateIssuePriority)
		r.Get("/{owner}/issues/{issueRef}/due-date/edit", s.uiEditIssueDueDate)
		r.Post("/{owner}/issues/{issueRef}/due-date", s.uiUpdateIssueDueDate)
		r.Get("/{owner}/issues/{issueRef}/assignee/edit", s.uiEditIssueAssignee)
		r.Post("/{owner}/issues/{issueRef}/assignee", s.uiUpdateIssueAssignee)
		r.Get("/{owner}/issues/{issueRef}/reporter/edit", s.uiEditIssueReporter)
		r.Post("/{owner}/issues/{issueRef}/reporter", s.uiUpdateIssueReporter)
		r.Get("/{owner}/issues/{issueRef}/sprint/edit", s.uiEditIssueSprint)
		r.Post("/{owner}/issues/{issueRef}/sprint", s.uiUpdateIssueSprint)
		r.Get("/{owner}/issues/{issueRef}/links/new", s.uiNewIssueLink)
		r.Post("/{owner}/issues/{issueRef}/links", s.uiCreateIssueLink)
		r.Get("/{owner}/issues/{issueRef}/links/{linkRef}/edit", s.uiEditIssueLink)
		r.Post("/{owner}/issues/{issueRef}/links/{linkRef}", s.uiUpdateIssueLink)
		r.Post("/{owner}/issues/{issueRef}/links/{linkRef}/delete", s.uiDeleteIssueLink)
		r.Get("/{owner}/issues/{issueRef}/sub-issues/new", s.uiNewSubIssue)
		r.Post("/{owner}/issues/{issueRef}/sub-issues", s.uiCreateSubIssue)
		r.Post("/{owner}/issues/{issueRef}/comments", s.uiCreateComment)
		r.Get("/{owner}/issues/{issueRef}/comments/{commentRef}/edit", s.uiEditComment)
		r.Post("/{owner}/issues/{issueRef}/comments/{commentRef}", s.uiUpdateComment)
		r.Post("/{owner}/issues/{issueRef}/attachments", s.uiCreateIssueAttachment)
		r.Get("/{owner}/issues/{issueRef}/attachments/{objectRef}/content", s.uiGetIssueAttachmentContent)
		r.Post("/{owner}/issues/{issueRef}/attachments/{objectRef}/delete", s.uiDeleteIssueAttachment)
		r.Delete("/{owner}/issues/{issueRef}/attachments/{objectRef}", s.uiDeleteIssueAttachmentJSON)
		r.Get("/{owner}/issues/{issueRef}/context", s.uiViewIssueContext)
		r.Get("/{owner}/issues/{issueRef}/context/link", s.uiNewIssueContextLink)
		r.Get("/{owner}/issues/{issueRef}/context/new", s.uiNewIssueContext)
		r.Post("/{owner}/issues/{issueRef}/context", s.uiCreateIssueContextLink)
		r.Get("/{owner}/issues/{issueRef}/context/{contextRef}", s.uiViewIssueContextItem)
		r.Get("/{owner}/issues/{issueRef}/context/{contextRef}/edit", s.uiEditIssueContext)
		r.Post("/{owner}/issues/{issueRef}/context/{contextRef}", s.uiUpdateIssueContext)
		r.Post("/{owner}/issues/{issueRef}/context/{contextRef}/delete", s.uiDeleteIssueContextLink)
		r.Get("/{owner}/issues/{issueRef}/tags", s.uiIssueTagsPage)
		r.Post("/{owner}/issues/{issueRef}/tags", s.uiAttachIssueTag)
		r.Post("/{owner}/issues/{issueRef}/tags/{tagRef}/delete", s.uiDetachIssueTag)
		r.Get("/{owner}/projects/{key}", s.uiProjectPage)
		r.Get("/{owner}/projects/{key}/about", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "about") })
		r.Get("/{owner}/projects/{key}/about/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "about") })
		r.Get("/{owner}/projects/{key}/tags", s.uiProjectTagsPage)
		r.Post("/{owner}/projects/{key}/tags", s.uiCreateProjectTag)
		r.Get("/{owner}/projects/{key}/tags/{tagRef}/edit", s.uiEditProjectTag)
		r.Post("/{owner}/projects/{key}/tags/{tagRef}", s.uiUpdateProjectTag)
		r.Post("/{owner}/projects/{key}/tags/{tagRef}/delete", s.uiDeleteProjectTag)
		r.Get("/{owner}/projects/{key}/context", s.uiProjectContextPage)
		r.Get("/{owner}/projects/{key}/context/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "context") })
		r.Get("/{owner}/projects/{key}/context/new", s.uiNewProjectContext)
		r.Post("/{owner}/projects/{key}/context", s.uiCreateProjectContext)
		r.Get("/{owner}/projects/{key}/context/{contextRef}", s.uiViewProjectContext)
		r.Get("/{owner}/projects/{key}/context/{contextRef}/panel", s.uiViewProjectContext)
		r.Get("/{owner}/projects/{key}/context/{contextRef}/edit", s.uiEditProjectContext)
		r.Post("/{owner}/projects/{key}/context/{contextRef}", s.uiUpdateProjectContext)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/delete", s.uiDeleteProjectContext)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/move-up", s.uiMoveProjectContextUp)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/move-down", s.uiMoveProjectContextDown)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/attachments", s.uiCreateContextAttachment)
		r.Get("/{owner}/projects/{key}/context/{contextRef}/attachments/{objectRef}/content", s.uiGetContextAttachmentContent)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/attachments/{objectRef}/delete", s.uiDeleteContextAttachment)
		r.Delete("/{owner}/projects/{key}/context/{contextRef}/attachments/{objectRef}", s.uiDeleteContextAttachmentJSON)
		r.Get("/{owner}/projects/{key}/context/{contextRef}/issues/new", s.uiNewProjectContextIssueLink)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/issues", s.uiCreateProjectContextIssueLink)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/issues/{issueRef}/delete", s.uiDeleteProjectContextIssueLink)
		r.Get("/{owner}/projects/{key}/name/edit", s.uiEditProjectName)
		r.Post("/{owner}/projects/{key}/name", s.uiUpdateProjectName)
		r.Post("/{owner}/projects/{key}/favorite", s.uiToggleProjectFavorite)
		r.Get("/{owner}/projects/{key}/description/edit", s.uiEditProjectDescription)
		r.Post("/{owner}/projects/{key}/description", s.uiUpdateProjectDescription)
		r.Post("/{owner}/projects/{key}/attachments", s.uiCreateProjectAttachment)
		r.Get("/{owner}/projects/{key}/attachments/{objectRef}/content", s.uiGetProjectAttachmentContent)
		r.Post("/{owner}/projects/{key}/attachments/{objectRef}/delete", s.uiDeleteProjectAttachment)
		r.Delete("/{owner}/projects/{key}/attachments/{objectRef}", s.uiDeleteProjectAttachmentJSON)
		r.Get("/{owner}/projects/{key}/sprints/new", s.uiNewProjectSprint)
		r.Post("/{owner}/projects/{key}/sprints", s.uiCreateProjectSprint)
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/edit", s.uiEditProjectSprint)
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/description", s.uiProjectSprintDescription)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}", s.uiUpdateProjectSprint)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/attachments", s.uiCreateSprintAttachment)
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/attachments/{objectRef}/content", s.uiGetSprintAttachmentContent)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/attachments/{objectRef}/delete", s.uiDeleteSprintAttachment)
		r.Delete("/{owner}/projects/{key}/sprints/{sprintRef}/attachments/{objectRef}", s.uiDeleteSprintAttachmentJSON)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/activate", s.uiActivateProjectSprint)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/complete", s.uiCompleteProjectSprint)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/delete", s.uiDeleteProjectSprint)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/move-up", s.uiMoveProjectSprintUp)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/move-down", s.uiMoveProjectSprintDown)
		r.Get("/{owner}/projects/{key}/sprints/{sprintRef}/issues/new", s.uiNewProjectSprintIssue)
		r.Post("/{owner}/projects/{key}/sprints/{sprintRef}/issues", s.uiAddProjectSprintIssue)
		r.Get("/{owner}/projects/{key}/issues/new", s.uiNewProjectIssuePage)
		r.Get("/{owner}/projects/{key}/issues/new/panel", s.uiNewProjectIssuePanel)
		r.Post("/{owner}/projects/{key}/issues", s.uiCreateProjectIssue)
		r.Get("/{owner}/projects/{key}/sprint", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "sprint") })
		r.Get("/{owner}/projects/{key}/sprint/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "sprint") })
		r.Get("/{owner}/projects/{key}/planned", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "planned") })
		r.Get("/{owner}/projects/{key}/planned/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "planned") })
		r.Get("/{owner}/projects/{key}/all", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "all") })
		r.Get("/{owner}/projects/{key}/all/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "all") })
		r.Get("/{owner}/projects/{key}/all/page", s.uiProjectAllIssuePage)
		r.Get("/{owner}/projects/{key}/changelog", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "changelog") })
		r.Get("/{owner}/projects/{key}/changelog/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "changelog") })
		r.Get("/{owner}/projects/{key}/changelog/page", s.uiProjectChangelogPage)
		r.Get("/{owner}/projects/{key}/backlog", func(w http.ResponseWriter, r *http.Request) { s.uiProjectLegacyBacklog(w, r, false) })
		r.Get("/{owner}/projects/{key}/backlog/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectLegacyBacklog(w, r, true) })
		r.Get("/{owner}/projects/{key}/deleted", s.uiProjectDeletedPage)
		r.Get("/{owner}/projects/{key}/deleted/panel", s.uiProjectDeletedPanel)
	})
}
