package server

import (
	"github.com/go-chi/chi/v5"
	"net/http"
)

func (s *Server) mountUIRoutes(r chi.Router) {
	r.Get("/login", s.uiLoginPage)
	r.Post("/login", s.uiLogin)
	r.Get("/signup", s.uiSignupPage)
	r.Post("/signup", s.uiSignup)
	r.Post("/logout", s.uiLogout)

	r.Group(func(r chi.Router) {
		r.Use(s.uiAuthMiddleware)
		r.Get("/", s.uiHome)
		r.Get("/me", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPage(w, r, "active") })
		r.Get("/me/panel", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPanel(w, r, "active") })
		r.Get("/me/all", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPage(w, r, "all") })
		r.Get("/me/all/panel", func(w http.ResponseWriter, r *http.Request) { s.uiWorkPanel(w, r, "all") })
		r.Get("/projects", s.uiProjectsPage)
		r.Get("/projects/panel", s.uiProjectsPanel)
		r.Get("/projects/new", s.uiNewProjectPage)
		r.Get("/projects/new/panel", s.uiNewProjectPanel)
		r.Post("/projects", s.uiCreateProject)
		r.Get("/issues/new", s.uiNewIssuePage)
		r.Get("/issues/new/panel", s.uiNewIssuePanel)
		r.Get("/issues/new/projects", s.uiNewIssueProjectOptions)
		r.Post("/issues", s.uiCreateIssue)
		r.Get("/settings", s.uiSettingsPage)
		r.Post("/settings/profile", s.uiUpdateProfile)
		r.Post("/settings/password", s.uiUpdatePassword)
		r.Get("/tokens", s.uiTokensPage)
		r.Post("/tokens", s.uiCreateToken)
		r.Post("/tokens/{id}/revoke", s.uiRevokeToken)
		if s.hub != nil {
			r.Get("/realtime", s.uiRealtime)
		}
		r.Get("/{owner}/issues/{issueRef}", s.uiIssuePage)
		r.Get("/{owner}/issues/{issueRef}/panel", s.uiIssuePanel)
		r.Post("/{owner}/issues/{issueRef}/delete", s.uiDeleteIssue)
		r.Post("/{owner}/issues/{issueRef}/restore", s.uiRestoreIssue)
		r.Get("/{owner}/issues/{issueRef}/title/edit", s.uiEditIssueTitle)
		r.Post("/{owner}/issues/{issueRef}/title", s.uiUpdateIssueTitle)
		r.Get("/{owner}/issues/{issueRef}/description/edit", s.uiEditIssueDescription)
		r.Post("/{owner}/issues/{issueRef}/description", s.uiUpdateIssueDescription)
		r.Get("/{owner}/issues/{issueRef}/status/edit", s.uiEditIssueStatus)
		r.Post("/{owner}/issues/{issueRef}/status", s.uiUpdateIssueStatus)
		r.Get("/{owner}/issues/{issueRef}/close-reason/edit", s.uiEditIssueCloseReason)
		r.Post("/{owner}/issues/{issueRef}/close-reason", s.uiUpdateIssueCloseReason)
		r.Get("/{owner}/issues/{issueRef}/priority/edit", s.uiEditIssuePriority)
		r.Post("/{owner}/issues/{issueRef}/priority", s.uiUpdateIssuePriority)
		r.Get("/{owner}/issues/{issueRef}/due-date/edit", s.uiEditIssueDueDate)
		r.Post("/{owner}/issues/{issueRef}/due-date", s.uiUpdateIssueDueDate)
		r.Get("/{owner}/issues/{issueRef}/assignee/edit", s.uiEditIssueAssignee)
		r.Post("/{owner}/issues/{issueRef}/assignee", s.uiUpdateIssueAssignee)
		r.Get("/{owner}/issues/{issueRef}/reporter/edit", s.uiEditIssueReporter)
		r.Post("/{owner}/issues/{issueRef}/reporter", s.uiUpdateIssueReporter)
		r.Get("/{owner}/issues/{issueRef}/sprint/edit", s.uiEditIssueSprint)
		r.Post("/{owner}/issues/{issueRef}/sprint", s.uiUpdateIssueSprint)
		r.Get("/{owner}/issues/{issueRef}/links/new", s.uiNewIssueLink)
		r.Post("/{owner}/issues/{issueRef}/links", s.uiCreateIssueLink)
		r.Get("/{owner}/issues/{issueRef}/links/{linkRef}/edit", s.uiEditIssueLink)
		r.Post("/{owner}/issues/{issueRef}/links/{linkRef}", s.uiUpdateIssueLink)
		r.Post("/{owner}/issues/{issueRef}/links/{linkRef}/delete", s.uiDeleteIssueLink)
		r.Get("/{owner}/issues/{issueRef}/sub-issues/new", s.uiNewSubIssue)
		r.Post("/{owner}/issues/{issueRef}/sub-issues", s.uiCreateSubIssue)
		r.Post("/{owner}/issues/{issueRef}/comments", s.uiCreateComment)
		r.Get("/{owner}/issues/{issueRef}/comments/{commentRef}/edit", s.uiEditComment)
		r.Post("/{owner}/issues/{issueRef}/comments/{commentRef}", s.uiUpdateComment)
		r.Get("/{owner}/issues/{issueRef}/context", s.uiViewIssueContext)
		r.Get("/{owner}/issues/{issueRef}/context/link", s.uiNewIssueContextLink)
		r.Get("/{owner}/issues/{issueRef}/context/new", s.uiNewIssueContext)
		r.Post("/{owner}/issues/{issueRef}/context", s.uiCreateIssueContextLink)
		r.Get("/{owner}/issues/{issueRef}/context/{contextRef}", s.uiViewIssueContextItem)
		r.Get("/{owner}/issues/{issueRef}/context/{contextRef}/edit", s.uiEditIssueContext)
		r.Post("/{owner}/issues/{issueRef}/context/{contextRef}", s.uiUpdateIssueContext)
		r.Post("/{owner}/issues/{issueRef}/context/{contextRef}/delete", s.uiDeleteIssueContextLink)
		r.Get("/{owner}/issues/{issueRef}/tags", s.uiIssueTagsPage)
		r.Post("/{owner}/issues/{issueRef}/tags", s.uiAttachIssueTag)
		r.Post("/{owner}/issues/{issueRef}/tags/{tagRef}/delete", s.uiDetachIssueTag)
		r.Get("/{owner}/projects/{key}", s.uiProjectPage)
		r.Get("/{owner}/projects/{key}/about", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "about") })
		r.Get("/{owner}/projects/{key}/about/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "about") })
		r.Get("/{owner}/projects/{key}/tags", s.uiProjectTagsPage)
		r.Post("/{owner}/projects/{key}/tags", s.uiCreateProjectTag)
		r.Get("/{owner}/projects/{key}/tags/{tagRef}/edit", s.uiEditProjectTag)
		r.Post("/{owner}/projects/{key}/tags/{tagRef}", s.uiUpdateProjectTag)
		r.Post("/{owner}/projects/{key}/tags/{tagRef}/delete", s.uiDeleteProjectTag)
		r.Get("/{owner}/projects/{key}/context", s.uiProjectContextPage)
		r.Get("/{owner}/projects/{key}/context/new", s.uiNewProjectContext)
		r.Post("/{owner}/projects/{key}/context", s.uiCreateProjectContext)
		r.Get("/{owner}/projects/{key}/context/{contextRef}/edit", s.uiEditProjectContext)
		r.Post("/{owner}/projects/{key}/context/{contextRef}", s.uiUpdateProjectContext)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/delete", s.uiDeleteProjectContext)
		r.Get("/{owner}/projects/{key}/context/{contextRef}/issues/new", s.uiNewProjectContextIssueLink)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/issues", s.uiCreateProjectContextIssueLink)
		r.Post("/{owner}/projects/{key}/context/{contextRef}/issues/{issueRef}/delete", s.uiDeleteProjectContextIssueLink)
		r.Get("/{owner}/projects/{key}/issues/new", s.uiNewProjectIssuePage)
		r.Get("/{owner}/projects/{key}/issues/new/panel", s.uiNewProjectIssuePanel)
		r.Post("/{owner}/projects/{key}/issues", s.uiCreateProjectIssue)
		r.Get("/{owner}/projects/{key}/sprint", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "sprint") })
		r.Get("/{owner}/projects/{key}/sprint/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "sprint") })
		r.Get("/{owner}/projects/{key}/planned", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "planned") })
		r.Get("/{owner}/projects/{key}/planned/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "planned") })
		r.Get("/{owner}/projects/{key}/all", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "all") })
		r.Get("/{owner}/projects/{key}/all/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "all") })
		r.Get("/{owner}/projects/{key}/all/page", s.uiProjectAllIssuePage)
		r.Get("/{owner}/projects/{key}/changelog", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPage(w, r, "changelog") })
		r.Get("/{owner}/projects/{key}/changelog/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectWorkPanel(w, r, "changelog") })
		r.Get("/{owner}/projects/{key}/changelog/page", s.uiProjectChangelogPage)
		r.Get("/{owner}/projects/{key}/backlog", func(w http.ResponseWriter, r *http.Request) { s.uiProjectLegacyBacklog(w, r, false) })
		r.Get("/{owner}/projects/{key}/backlog/panel", func(w http.ResponseWriter, r *http.Request) { s.uiProjectLegacyBacklog(w, r, true) })
		r.Get("/{owner}/projects/{key}/deleted", s.uiProjectDeletedPage)
		r.Get("/{owner}/projects/{key}/deleted/panel", s.uiProjectDeletedPanel)
	})
}
